/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NativeRouteImport } from './routes/native'
import { Route as ReadBookIdRouteImport } from './routes/read.$bookId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiNativeV1SplatRouteImport } from './routes/api/native/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NativeRoute = NativeRouteImport.update({
  id: '/native',
  path: '/native',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookIdRoute = ReadBookIdRouteImport.update({
  id: '/read/$bookId',
  path: '/read/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNativeV1SplatRoute = ApiNativeV1SplatRouteImport.update({
  id: '/api/native/v1/$',
  path: '/api/native/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/native': typeof NativeRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/native/v1/$': typeof ApiNativeV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/native': typeof NativeRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/native/v1/$': typeof ApiNativeV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/native': typeof NativeRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/native/v1/$': typeof ApiNativeV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/native'
    | '/read/$bookId'
    | '/api/auth/$'
    | '/api/native/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/native'
    | '/read/$bookId'
    | '/api/auth/$'
    | '/api/native/v1/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/native'
    | '/read/$bookId'
    | '/api/auth/$'
    | '/api/native/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NativeRoute: typeof NativeRoute
  ReadBookIdRoute: typeof ReadBookIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNativeV1SplatRoute: typeof ApiNativeV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/native': {
      id: '/native'
      path: '/native'
      fullPath: '/native'
      preLoaderRoute: typeof NativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookId': {
      id: '/read/$bookId'
      path: '/read/$bookId'
      fullPath: '/read/$bookId'
      preLoaderRoute: typeof ReadBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/native/v1/$': {
      id: '/api/native/v1/$'
      path: '/api/native/v1/$'
      fullPath: '/api/native/v1/$'
      preLoaderRoute: typeof ApiNativeV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NativeRoute: NativeRoute,
  ReadBookIdRoute: ReadBookIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNativeV1SplatRoute: ApiNativeV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
